SET REFERENTIAL_INTEGRITY FALSE;

DELETE FROM ATTEMPT;
DELETE FROM ATTEMPT_ANSWER;

ALTER SEQUENCE SQ_ATTEMPT_ANSWER_PK RESTART WITH 1;
ALTER SEQUENCE SQ_ATTEMPT_PK RESTART WITH 1;

INSERT INTO ATTEMPT (ATTEMPT_ID, ACCOUNT_ID, QUIZ_ID, SCORE, ISCOMPLETE)
VALUES (SQ_ATTEMPT_PK.NEXTVAL, 1, 10, 80, TRUE);

INSERT INTO ATTEMPT (ATTEMPT_ID, ACCOUNT_ID, QUIZ_ID, SCORE, ISCOMPLETE)
VALUES (SQ_ATTEMPT_PK.NEXTVAL, 1, 20, 75, TRUE);

INSERT INTO ATTEMPT (ATTEMPT_ID, ACCOUNT_ID, QUIZ_ID, SCORE, ISCOMPLETE)
VALUES (SQ_ATTEMPT_PK.NEXTVAL, 1, 30, 50, FALSE);

INSERT INTO ATTEMPT (ATTEMPT_ID, ACCOUNT_ID, QUIZ_ID, SCORE, ISCOMPLETE)
VALUES (SQ_ATTEMPT_PK.NEXTVAL, 2, 5, 80, FALSE);
